_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
backend:
    value: Aer Statevector
circuit_depth:
    value: 5
circuit_type:
    value: Bell State
n_qubits:
    value: 3
shots:
    value: 1024
